aPI/urls.py
from django.urls import path
from api import views


urlpatterns = [
    path("api/users/", views.getUsers, name="getUsers"),
    path("api/users/<int:pk>/", views.getUser, name="getUser"),
    path("api/accounts/", views.getAccounts, name="getAccounts"),
    path("api/accounts/<int:pk>/", views.getAccount, name="getAccount"),
    path("api/accounts/<int:pk>/items/", views.getAccountItems, name="getAccountItems"),
    path("api/items/", views.getItems, name="getItems"),
    path("api/items/<int:pk>/", views.getItem, name="getItem"),
    path("api/users/create/", views.createUser, name="createUser"),
    path("api/items/create/", views.createItem, name="createItem"),
    path("api/items/<int:pk>/bid/", views.submitBid, name="submitBid"),
    path("api/users/<int:pk>/del/", views.delUser, name="delUser"),
    path("api/items/<int:pk>/del/", views.delItem, name="delItem"),
    path("api/login/", views.login, name="tokenLogin"),
    path("api/logout/", views.logout, name="tokenLogout"),
    path("api/amITheBuyer/<int:pk>/", views.amITheBuyer, name="amITheBuyer"),
    path("api/accountBids/<int:pk>/", views.getItemsBidOnByMe, name="getItemsBidOnByMe"),
]

base/urls.py
from django.urls import path
from base import views

urlpatterns = [
    path("", views.homeView, name="home"),
    path("login/", views.loginView, name="login"),
    path("logout/", views.logoutView, name="logout"),
    path("about/", views.about, name="about"),
    path("userBids/", views.userBids, name="userBids"),
    path("userListings/<int:pk>/", views.userListings, name="userListings"),
    path("browse/page<int:page>/", views.browse, name="browse"),
    path("listAnItem/", views.listAnItem, name="listAnItem"),
    path("browse/<int:pk>/", views.itemDetail, name="itemDetail"),
    path("listAnItem/itemListed/<int:pk>/", views.itemListed, name="itemListed"),
]

webProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("base.urls")),
    path("", include("api.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db.models import CheckConstraint, Q
import json

class Account(models.Model): 
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    address=models.CharField(max_length=200)
    balance=models.DecimalField(decimal_places=2, max_digits=10, default=0, validators=[MinValueValidator(0)])
    fcmToken=models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        constraints = (
            CheckConstraint(
                check=Q(balance__gte=0), 
                name="minBalance"),
            )

    def __str__(self):
        return f'{self.id}: {self.user.username}'
    
class Item(models.Model): 
    name = models.CharField(max_length=60)
    price = models.DecimalField(decimal_places=2, max_digits=7)
    postageCost = models.DecimalField(decimal_places=2, max_digits=6)
    bidIncrement = models.DecimalField(decimal_places=2, max_digits=6)
    conditionChoices = [
        ("new", "New"),
        ("excellent", "Excellent"),
        ("good", "Good"),
        ("used", "Used"),
        ("refurbished", "Refurbished"),
        ("partsOnly", "Parts Only"),
    ]
    condition = models.CharField(max_length=20, choices=conditionChoices)
    endDateTime = models.DateTimeField()
    acceptReturns = models.BooleanField(default=False)
    description = models.TextField(max_length=1000)
    numBids = models.IntegerField(default=0)
    bidders = models.CharField(max_length=999999999, default='[]')
    ended = models.BooleanField(default=False)
    sold = models.BooleanField(default=False)
    buyer = models.ForeignKey(Account, to_field="id", on_delete=models.DO_NOTHING, related_name="bId", blank=True, null=True)
    seller = models.ForeignKey(Account, to_field="id", on_delete=models.DO_NOTHING, related_name="sId", blank=True, null=True)
    destinationAddress = models.CharField(max_length=200, blank=True, null=True)
    transactionSuccess = models.BooleanField(blank=True, null=True)
    categories = [
        ("bOIS", "Business, Office & Industrial Supplies"),
        ("hB", "Health & Beauty"),
        ("f", "Fashion"),
        ("e", "Electronics"),
        ("hG", "Home Garden"),
        ("sHL", "Sports, Hobbies & Leisure"),
        ("mt", "Motors"),
        ("cA", "Collectables & Art"),
        ("mda", "Media"),
        ("o", "Other"),
    ]
    category = models.CharField(max_length=50, choices=categories)
    subCategory = models.CharField(max_length=50, blank=True, null=True)
 
    def getBidders(self):
        return json.loads(self.bidders)
    
    def setBidders(self, value):
        self.bidders = json.dumps(value)

    biddersProperty = property(getBidders, setBidders)

    def __str__(self):
        return f'{self.id}: {self.name}'

class IMDb(models.Model):
    id = models.CharField(max_length=20, primary_key=True)
    title = models.CharField(max_length=300)
    year = models.IntegerField()
    certificate = models.CharField(max_length=10)
    rating = models.DecimalField(decimal_places=1, max_digits=5)
    votes = models.IntegerField()
    rank = models.IntegerField()
    genres = models.CharField(max_length=300)
    summary = models.CharField(max_length=1000)
    writers = models.CharField(max_length=500)
    directors = models.CharField(max_length=500)
    stars = models.CharField(max_length=300)
    runtime = models.IntegerField()
    type = models.CharField(max_length=50)
    aspectRatio = models.DecimalField(decimal_places=2, max_digits=4)
    posterUrl = models.CharField(max_length=300)

    def getField(self, field):
        if field == 'genres':
            toLoad = self.genres
        elif field == 'writers':
            toLoad = self.writers
        elif field == 'directors':
            toLoad = self.directors
        elif field == 'stars':
            toLoad = self.stars
        
        return json.loads(toLoad)

    def __str__(self):
        return f'{self.id}: {self.title} ({self.year})'

base/views.py
import ast
from datetime import datetime, timedelta
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.utils import timezone
from django.shortcuts import redirect
from django.db.models import Q
from .models import Item, Account
from .forms import ItemForm, BrowseForm, BidForm
from django.db.models.functions import Lower
from firebase_admin import storage

bucket = storage.bucket()
toBool = {
    'true': True,
    'false': False,
}
def getBaseUrl(request):
    baseUrl = f"{request.scheme}://{request.get_host()}"
    return baseUrl

def getLoginPath(request):
    loginParams = request.GET.copy()
    loginParams.update({
        "path": request.path,
    })
    loginPath = f"/login/?{loginParams.urlencode()}"
    return loginPath

def getDownloadUrl(path):
    blob = bucket.blob(path)
    url = blob.generate_signed_url(datetime.utcnow() + timedelta(hours=1))
    return url

def getUsernameBalance(request):
    username = None
    balance = None
    user = request.user
    if user.is_authenticated:
        username = user.username
        balance = Account.objects.get(user=user).balance
    return (username, balance)

def homeView(request):
    username, balance = getUsernameBalance(request)
    items = Item.objects.filter(sold=True).order_by("-endDateTime")[:100]
    for item in items:
        item.bidders = getDownloadUrl(f"uploads/images/{item.id}/thumbNail")
    context = {
        "items": items,
        "username": username,
        "balance": balance,
        "home": True,
    }
    return render(request, 'base/browse.html', context)

AuthenticationForm.error_messages = {
    "invalid_login": "Invalid username and/or password.",
    "inactive": "This account is inactive."
}

def loginView(request):
    loginParams = request.GET.copy()
    path = loginParams.get("path")
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                if path is not None:
                    if path == "/userListings/0/":
                        path = f"/userListings/{user.pk}/"
                    return redirect(path)
                else: 
                    return redirect("/")
            else:
                username = None
                return render(request, "base/login.html", {"form": form, "username": username})
    else:
        form = AuthenticationForm()
    username, balance = getUsernameBalance(request)
    return render(request, "base/login.html", {"form": form, "username": username, "balance": balance})
     
def logoutView(request): 
    logout(request)
    return redirect("/")

def itemDetail(request, pk):
    username, balance = getUsernameBalance(request)
    url = getDownloadUrl(f'uploads/images/{pk}/smallerImage')
    if request.method == "POST":
        bidForm = BidForm(request.POST)
        item = get_object_or_404(Item.objects.filter(ended=False), pk=pk)
        if request.user.is_authenticated:
            if bidForm.is_valid():
                account = Account.objects.get(user=request.user)
                bid = bidForm.cleaned_data["bid"]
                minPrice = item.price + item.bidIncrement
                buyerId = account.id
                sellerId = item.seller_id
                if bid >= minPrice and balance >= bid and buyerId != sellerId and timezone.now() < item.endDateTime:
                    item.price = bid
                    item.numBids += 1
                    item.buyer = account
                    bidders=item.getBidders()
                    bidders.append(item.buyer_id)
                    item.setBidders(bidders)
                    item.save()
                    message = "Bid Submitted."
                elif buyerId == sellerId:
                    message = "Could not submit bid: you listed this item."
                elif timezone.now() >= item.endDateTime:
                    message = "Could not submit bid: listing has ended."
                elif bid < minPrice:
                    message = "Could not submit bid: bid < £" + str(minPrice) + "."
                elif bid > balance:
                    message = "Could not submit bid: balance < bid."
                balance = getUsernameBalance(request)[1]
                context={"bidForm": bidForm, "item": item, "username": username, "balance": balance, "message": message, "imgUrl": url,}
            else: 
                item = get_object_or_404(Item.objects.filter(ended=False), pk=pk)
                bidForm = BidForm()
                context={"bidForm": bidForm, "item": item, "username": username, "balance": balance, "imgUrl": url,}
        else:
            loginPath = getLoginPath(request)
            return redirect(loginPath)
    else:
        item = get_object_or_404(Item.objects.all(), pk=pk)
        bidForm = BidForm()
        context={"bidForm": bidForm, "item": item, "username": username, "balance": balance, "imgUrl": url,}
    active = not item.ended
    context["active"] = active
    return render(request, "base/itemDetail.html", context)
    

def about(request):
    username, balance = getUsernameBalance(request)
    return render(request, "base/about.html", {"username": username, "balance": balance})

def userBids(request):
    if not request.user.is_authenticated:
        loginPath = getLoginPath(request)
        return redirect(loginPath)
    username, balance = getUsernameBalance(request)
    items = Item.objects.filter(ended=False).order_by("endDateTime")
    myCurrentItems = []
    for item in items:
        if request.user.pk in item.getBidders():
            myCurrentItems.append(item)
    eItems = Item.objects.filter(ended=True).order_by("-endDateTime")
    myOldItems = []
    for item in eItems:
        if request.user.pk in item.getBidders():
            myOldItems.append(item)

    return render(
        request, "base/userBids.html", 
        {
        "username": username,
        "balance": balance,
        "myCurrentItems": myCurrentItems, 
        "myOldItems": myOldItems,
        }
        )

def userListings(request, pk):
    if not request.user.is_authenticated and pk == 0:
        loginPath = getLoginPath(request)
        return redirect(loginPath)
    username, balance = getUsernameBalance(request)
    myCurrentItems = Item.objects.filter(Q(ended=False) & Q(seller=pk)).order_by("endDateTime")
    myOldItems = Item.objects.filter(Q(ended=True) & Q(seller=pk)).order_by("-endDateTime")
    you = True if request.user.pk == pk else False
    return render(
        request, "base/userListings.html", 
        {
        "username": username,
        "balance": balance,
        "myCurrentItems": myCurrentItems, 
        "myOldItems": myOldItems,
        "you": you,
        }
        )

def browse(request, page):
    searchParams = request.GET.copy()
    if request.method == "POST":
        browseForm = BrowseForm(request.POST)
        if browseForm.is_valid():
            conditionsFilter = ["", "", "", "", "", ""]
            for i in range(6):
                if browseForm.cleaned_data[browseForm.conditions[i]]:
                    conditionsFilter[i] = browseForm.conditions[i]
            searchParams.clear()
            searchParams.update({
                "search": browseForm.cleaned_data["search"],
                "category": browseForm.cleaned_data["category"],
                "sortBy": browseForm.cleaned_data["sortBy"],
                "asc": browseForm.cleaned_data["ascending"],
                "lT": browseForm.cleaned_data["lThan"],
                "gT": browseForm.cleaned_data["gThan"],
                "new": browseForm.cleaned_data["new"],
                "excellent": browseForm.cleaned_data["excellent"],
                "good": browseForm.cleaned_data["good"],
                "used": browseForm.cleaned_data["used"],
                "refurbished": browseForm.cleaned_data["refurbished"],
                "partsOnly": browseForm.cleaned_data["partsOnly"],
                "rA": browseForm.cleaned_data["areReturnsAccepted"],
                "rNA": browseForm.cleaned_data["areReturnsNotAccepted"],
                "n": browseForm.cleaned_data["showNItems"], 
                "conditionsFilter": conditionsFilter,
            })
            newUrl = f"{getBaseUrl(request)}/browse/page1/?{searchParams.urlencode()}"
            return redirect(newUrl)
        
    else:
        username, balance = getUsernameBalance(request)
        if len(searchParams) > 0:
            search = searchParams.get("search")
            category = searchParams.get("category")
            sortBy = searchParams.get("sortBy")
            ascending = toBool[searchParams.get("asc").lower()]
            lThan = float(searchParams.get("lT"))
            gThan = float(searchParams.get("gT"))
            areReturnsAccepted = toBool[searchParams.get("rA").lower()]
            areReturnsNotAccepted = toBool[searchParams.get("rNA").lower()]
            conditionsFilter = ast.literal_eval(searchParams.get("conditionsFilter"))
            n = int(searchParams.get("n"))
            minItem = page * n - n
            maxItem = page * n
            browseDict = {
                "search": search,
                "category": category,
                "sortBy": sortBy,
                "ascending": ascending,
                "lThan": lThan,
                "gThan": gThan,
                "areReturnsAccepted": areReturnsAccepted,

base/templates/base/about.html
{% extends "base/layout.html" %}
{% block title %}
    Auction - About Us
{% endblock %}

{% block loggedInAs %}
  {% include "base/status.html" %}
{% endblock %}

{% block content %}
    <p style="color: rgb(224, 224, 224); margin-top: -40px;">Auction site for pretty much anything.</p>
{% endblock %}

base/templates/base/browse.html
{% extends "base/layout.html" %}

{% block title %}
  Auction - Browse Items
{% endblock %}

{% block loggedInAs %}
  {% include "base/status.html" %}
{% endblock %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>
<script>
  $(document).ready(function() {
    $('#toggle').click(function() {
      $('#sortAndFilterByMenu').slideToggle();
    });
  });
</script>

<div style="margin-top: -60px; max-width: 1800px;">
  {% if not home %}
    {% if results > 100 %}
    <h2 style="text-align: center">
      Showing {{minItem}}-{{maxItem}} of {{results}} Results <button id="toggle" class="toggle">Toggle →</button>
    </h2>
    {% elif results == 0 %}
    <h2 style="text-align: center">
      No Results <button id="toggle" class="toggle">Toggle →</button>
    </h2>
    {% elif results == 1 %}
    <h2 style="text-align: center">
      {{results}} Result <button id="toggle" class="toggle">Toggle →</button>
    </h2>
    {% else %}
    <h2 style="text-align: center">
      {{results}} Results <button id="toggle" class="toggle">Toggle →</button>
    </h2>
    {% endif %}
  {% else %}
    <h2 style="text-align: center;">Recently Sold Items</h2>
  {% endif %}
  <div class="grid">
    <div class="gridCards">
      {% for item in items %}
        {% include "base/card.html" %}
      {% empty %}
        <p style="color: rgb(224, 224, 224)">No items found.</p>
      {% endfor %}
    </div>
  </div>
</div>

{% if not home %}
<div id="sortAndFilterByMenu" class="rightContainer" style="width: 280px; margin-top: -60px;">
  <h3 style="margin: 35px 0px 20px 0px;">Menu</h3>
  <form method="POST" class="sortAndFilterByMenu">
    {% csrf_token %}
    {{browseForm.as_p}}
    <hr color="black">
    <button type="submit" style="margin-bottom: 10px;">Apply</button>
  </form>
</div>
{% endif %}

<div style="clear: both;"></div>
{% endblock %}

{% block additionalContent %}
<br>
<div class="centralContainer">
  {% for page in pages %}
    {% if page == currentPage %}
      <li class="borderli" style="border-radius: 0; margin-right: 5px; font-weight: bold";>
        <a href="{% url 'browse' page=page %}">{{page}}</a>
      </li>
    {% else %}
      <li class="borderli" style="border-radius: 0; margin-right: 5px;">
        <a href="{% url 'browse' page=page %}?{{ searchParams }}">{{page}}</a>
      </li>
    {% endif %}
  {% endfor %}
</div>
{% endblock %}

base/templates/base/card.html
{% load static %}
<div class="textBlock" style="width: 400px; height: 220px; display: flex; align-items: center;">
    <div class="centralContainer" style="width: 400px; align-items: center;">
        <div class="leftContainer" style="width: 125px;  align-self: center; padding-left: 5px;">
            <img src="{{item.bidders}}" alt="thumbNail" style="width: 125px; display: flex;"/>
        </div>
        <div class="rightContainer" style="width: 250px; align-self: center; margin-left: 12px;">
            <a href="{% url 'itemDetail' pk=item.pk %}">{{item.name}}</a>
            <br>
            £{{ item.price }}
            <br>
            {{ item.numBids }} bids
            <br>
            {{ item.condition }}
            <br>
            Listed by {{ item.seller.user.username }}
        </div>
    </div>
</div>

base/templates/base/itemDetail.html
{% extends "base/layout.html" %}
{% load myTags %}

{% block title %}
Auction - {{item.name}}
{% endblock %}

{% block loggedInAs %}
  {% include "base/status.html" %}
{% endblock %}

{% block subheader %}
<h2 style="margin-top: -40px;">
  {{item.name}}
</h2> 
{% endblock %}

{% block content %}
<div class="leftContainer" style="max-width: 300px;">
  {% numToMoney item.price as currentPrice %}
  {% if active %}
    <p class="textBlock" style="max-width: 245px; line-height: 30px; padding: 10px 20px; margin: 0px 0px 0px 0px;">
      <strong>Summary:</strong><br>
      Current Price: £{{currentPrice}}<br>
      Postage Cost: £{{item.postageCost}}<br>
      Bid Increment: £{{item.bidIncrement}}<br>
      Condition: {{item.get_condition_display}}<br>
      End: {{item.endDateTime|date:"M d Y, H:i"}}<br>
      Accepts Returns: {% if item.acceptReturns %}Yes{% else %}No{% endif %}<br>
      Bids: {{item.numBids}}<br>
      {% idToUsername item.seller_id as sellerUsername %}
      {% if sellerUsername != username %}
        Seller: <a href="{% url 'userListings' pk=item.seller_id %}">{{sellerUsername}}</a>   
      {% else %}
        Seller: You
      {% endif %}
    </p>
  {% else %}
    <p class="textBlock" style="max-width: 260px; line-height: 30px; padding: 10px 20px; margin: 0px 0px 0px 0px;">
      <strong>Summary:</strong><br>
      Sale Price: £{{currentPrice}}<br>
      Postage Cost: £{{item.postageCost}}<br>
      Bid Increment: £{{item.bidIncrement}}<br>
      Condition: {{item.get_condition_display}}<br>
      End: {{item.endDateTime|date:"M d Y, H:i"}}<br>
      Accepts Returns: {% if item.acceptReturns %}Yes{% else %}No{% endif %}<br>
      Bids: {{item.numBids}}<br>
      {% idToUsername item.seller_id as sellerUsername %}
      {% if sellerUsername != username %}
        Seller: <a href="{% url 'userListings' pk=item.seller_id %}">{{sellerUsername}}</a>   
      {% else %}
        Seller: You
      {% endif %}
    </p>
  {% endif %}
</div>

<div class="rightContainer" style="max-width: 50vw;">
  <p class="textBlock" style="line-height: 30px; padding: 10px 20px; margin: 0px 0px 0px 0px;">
    <strong style="margin-top: 0px;">Description:</strong><br>
    <span style="white-space: pre-line;">{{item.description}}</span>
  </p>
</div>

<div style="clear: both;"></div>
{% endblock %}

{% block additionalContent %}
{% if active %}
<div class="centralContainer">
  <form method="POST" class="submitBid">
    {% csrf_token %}
    {{bidForm.as_p}}
    <button type="submit">Submit Bid</button>
    <br>
    <strong style="color: rgb(224, 224, 224); text-align: center;">{{message}}</strong>
  </form>  
</div>
{% else %}
<br>
{% endif %}
<div class="centralContainer" style="margin-top: 5px">
  <img src="{{imgUrl}}" alt="Image" style="width: 600px;"/>
</div>
<br>
{% endblock %}

base/templates/base/itemListed.html
{% extends "base/layout.html" %}
{% block title %}
    Auction - Item Listed
{% endblock %}

{% block loggedInAs %}
  {% include "base/status.html" %}
{% endblock %}

{% block content %}
    <p style="margin-top: -40px; color:rgb(224, 224, 224); text-align: center;">
        Your item: "{{item.name}}" has been listed.
        <br>
        <a href="{% url 'itemDetail' pk=item.pk %}">[Go to item listing]</a>
    </p>
{% endblock %}

base/templates/base/layout.html
<!DOCTYPE html>
<html>
<script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>
<script>
$(document).ready(function() {
    var url = window.location.pathname;
    if (url.includes('browse/page')) {
        $('#browse').addClass('navbarCurrent')
    }
    $('.navbarItem').each(function() {
        var link = $(this).attr('href');
        if (link === url) {
            $(this).addClass('navbarCurrent');
        }
    });
});
</script>  

<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'base/site.css' %}"/>
    <link rel="icon" href="{% static 'images/icon.png' %}" type="image/png" sizes="128x128"/>
</head>

<body>
<div class="navbar">
    <a href="{% url 'home' %}" id="home" class="navbarItem" style="margin-left: 0px;">Home</a>
    <a href="{% url 'userBids' %}" id="myBids" class="navbarItem">My Bids</a>
    {% if request.user.pk %}
    <a href="{% url 'userListings' pk=request.user.pk %}" id="myListings" class="navbarItem">My Listings</a>
    {% else %}
    <a href="{% url 'userListings' pk=0 %}" id="myListings" class="navbarItem">My Listings</a>
    {% endif %}
    <a href="{% url 'browse' page=1 %}" id="browse" class="navbarItem">Browse Items</a>
    <a href="{% url 'listAnItem' %}" id="listAnItem" class="navbarItem">List an Item</a>
    <a href="{% url 'about' %}" id="about" class="navbarItem">About</a>
</div>
   
<div>
    {% block loggedInAs %}
    {% endblock %}
</div>

<div class="centralContainer">
    {% block subheader %}
    {% endblock %}
</div>

<div class="centralContainer">
    {% block content %}
    {% endblock %}
</div>

{% block additionalContent %}
{% endblock %}

<hr/>
<footer style="color: rgb(224, 224, 224);">
    &copy; 2023
</footer>
</body>
</html>

base/templates/base/listAnItem.html
{% extends "base/layout.html" %}
{% block title %}
    Auction - List an Item
{% endblock %}

{% block loggedInAs %}
  {% include "base/status.html" %}
{% endblock %}

{% block subheader %}
    <h2 style="margin-top: -40px; margin-bottom: 0px;">List an Item</h2>
{% endblock %}

{% block content %}
    <form method="POST" class="listAnItem">
        {% csrf_token %}
        {{form.as_p}}
        <div class="centralContainer">
            <button type="submit">List Item</button>
        </div>        
    </form>
{% endblock %}

base/templates/base/logMessage.html
{% extends "base/layout.html" %}
{% block title %}
    Auction - Log a Message
{% endblock %}
{% block content %}
    <form method="POST" class="log-form">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="save btn btn-default">Log</button>
    </form>
{% endblock %}

base/templates/base/login.html
{% extends "base/layout.html" %}
{% block title %}
Auction - Login
{% endblock %}

{% block loggedInAs %}
    {% if username %}
    <p style="color: rgb(224, 224, 224)">
        Logged in as {{username}}. 
        <br>
        Balance: £{{balance}}
    </p>
    {% else %}
    <p style="color: rgb(224, 224, 224)">
        You are not logged in. 
    </p>
    {% endif %}
{% endblock %}

{% block content %}
<form method="POST" class="login">
    {% csrf_token %}
    {{form.as_p}}
    <hr color="black">
    <button type="submit" style="margin-bottom: 5px;">Login</button>
</form>
{% endblock %}

base/templates/base/status.html
{% if username %}
<p style="color: rgb(224, 224, 224)">
    {% load myTags %}
    Logged in as {{username}}. 
    <br>
    Balance: £{% numToMoney balance %}
    <br>
    <a href="{% url 'logout' %}">Logout</a>
</p>
{% else %}
<p style="color: rgb(224, 224, 224)">
    You are not logged in. 
    <br>
    <a href="{% url 'login' %}">Login</a>
</p>
{% endif %}